- name: Install Podman
  ansible.builtin.package:
    name: podman
    state: present
  become: true
  
- name: Ensure the podman user exists
  ansible.builtin.user:
    name: "{{ podman_user }}" # variable is dependent on the var in the playbook
    shell: /bin/bash
    state: present
  become: true
  
- name: Ensure podman service dirs exist
  file:
    path: /etc/containers
    state: directory
    mode: '0755'
